apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ondassynovdaulet
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/todo"
  SPRING_DATASOURCE_USERNAME: "postgres"
  APP_NAME: "todo-app-ondassynovdaulet"
