apiVersion: v1
kind: Service
metadata:
  name: todo-service-ondassynovdaulet
spec:
  type: NodePort
  selector:
    app: todo-ondassynovdaulet
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
